### PR TITLE
[FEAT][FIX] allow native time and offset + fix in DST

### PR DESCRIPTION
**Pull request by huafu**
This PR does the following:
- 🐛 fixes original tests (2 of them not passing right after git clone)
- 🐛 fixes a bug if the OS timezone has daylight saving (DST)
- ✨ allow `null` in `referenceTime` so that the realtime can be used while faking a timezone
- ✨ allow `null` in `timezoneOffset` to keep the system timezone
- ✨ adds TypeScript typings definition file
- ⬆️ upgrades versions of mocha and eslint
- 👕 adds `lint` script
- 🚨 updates `test` script so that it runs twice, once with `UTC`, and once with `Europe/Paris` (which is a timezone having DST)
- 🔧 adds repo, homepage & issues URLs in `package.json`

_FYI, there should be no breaking change (tests have been ran before starting to add stuff)_

### CODE REVIEW

**Comment by greim** [comment]
Thanks!

**Comment by huafu** [comment]
You're welcome!

I have something in my code to replace the global date object for testing, is that something I should bring to this repo as well?

**Comment by greim** [comment]
Naw, I'd prefer leaving it to end users to monkey-patch their own global objects. Might be helpful to add some code samples or how-tos though.

**Comment by huafu** [comment]
I was planning it as an opt-in. Like `fakeDate({..., overrideGlobal: true})`. So by default the lib will continue to act as it is now.

**Comment by huafu** [comment]
@greim can you make a new release and publish it to npm please?

**Comment by greim** [comment]
Currently traveling and will try to get to this soon. Also I'd like to get 2fa setup on my npm account before I do anything else, due to the recent eslint-scope security breach.

**Comment by huafu** [comment]
still traveling? 😁

**Pull request merged**
